[package]
name = "SomewhereAnywhereEngine"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
glfw = { version = "0.59", features = ["vulkan"] }
glfw-sys = "5.0.0"
vulkano = "0.35.1"
